Data Science and Machine Learning:
- tensorflow
- numpy
- machine-learning
- scikit-learn
- image
- nltk
- data-structures
- scipy
- ipython-notebook
- jupyter-notebook
- matplotlib
- deep-learning
- torch
- torchvision
- pytorch-lightning
- torchtext
- dataframe
- nlp
- neural-network
- data-science
- image-processing
- computer-vision
- pytorch
- classification
- gensim
- cluster-analysis
- statistics
- pandas
- opencv
- keras
- jupyter
- python-imaging-library
- algorithm
- conv-neural-network
Database and SQL:
- mysql
- database
- pandas
- sqlite
- sqlalchemy
- sql
- excel
- pyspark
- mongodb
- postgresql
- dataframe
- excel
- amazon-s3
- openerp
GUI and Desktop Applications:
- tkinter
- pyqt
- kivy
- wxpython
- pygame
- user-interface
- qt
- gui
- pyqt4
- pygtk
- wxwidgets
Networking and APIs:
- sockets
- json
- api
- http
- rest
- web-scraping
- parsing
- scrapy
- beautifulsoup
- github-api
- gitlab-api
- azure
- networking
- web-applications
- ajax
- security
Other:
- c++
- java
- performance
- installation
- file
- celery
- c#
- ruby
- unit-testing
- git
- c
- ide
- xml
- automation
- testing
- logging
- r
- selenium-webdriver
- unicode
- pdf
- node.js
- package
- email
- optimization
- wsgi
- authentication
- matlab
- deployment
- exe
- perl
- twitter
- pytest
- rabbitmq
- audio
- discord.py
- process
- time
- file-io
- emacs
- memory
- text
- gtk
Python Basics and Environment:
- python-3.x
- python-2.7
- python-3.6
- pip
- pycharm
- visual-studio
- arrays
- math
- py2exe
- oop
- anaconda
- virtualenv
- pyinstaller
- conda
- subprocess
- python-idle
- json
- pydev
- multiprocessing
- dictionary
- python-requests
- list
- string
- regex
- multithreading
- spyder
- path
- module
- import
- pickle
- function
- python-import
- random
- setuptools
- cmd
- class
- parallel-processing
- ipython
- visual-studio-code
- ironpython
- datetime
- asynchronous
- eclipse
- csv
System Administration and DevOps:
- windows
- linux
- google-app-engine
- amazon-web-services
- ubuntu
- android
- docker
- terminal
- aws-lambda
- command-line
- heroku
- networking
- amazon-ec2
- apache-spark
- debugging
- google-cloud-datastore
- google-cloud-platform
- server
- vim
- airflow
- unix
- scripting
- cron
- ssh
- .net
- macos
- docker
- apache
- nginx
- bash
- raspberry-pi
- shell
Version Control:
- git
- github
- gitlab
- git-bash
- gitpython
- gitignore
- gitlab-ci
- github3.py
- git-submodules
- github-pages
- github-api
- github-actions
- github-for-mac
- git-commit
- gitlab-api
- githooks
- git-rebase
- git-pull
- git-merge-conflict
- git-review
- github-copilot
- git-webhooks
- python-gitlab
- git-clone
- github-for-windows
- github-desktop
- git-diff
- git-config
- git-bisect
- git-push
Web Development:
- django
- flask
- javascript
- html
- css
- php
- selenium
- django-models
- apache
- ruby
- sqlalchemy
- rest
- django-rest-framework
- django-admin
- ajax
- tornado
- web
- web-applications
- http
- django-templates
- twisted
- pyramid
- mod-wsgi
