model_run_name:
  adapter_type: "Lora"
  domain_class: "GUI_Desktop_Applications"
  main_model: "llama-7b-hf"

model:
  name: "/raid/models/llama-7b-hf" # путь файлов модели
  load_in_8bit: true
  peft_model_id: null # указать, чтобы загрузить Peft веса с HF
  torch_dtype: fp16 # fp16/null - dtype модели
  device_map: auto # cuda:2
  padding_side: left # try right

lora_config:
  r: 8
  lora_alpha: 32
  lora_dropout: 0.1
  bias: "none"

ptune_config:
  num_virtual_tokens: 512
  #token_dim: 4096
  num_transformer_submodules: 1
  #num_attention_heads: 12
  #num_layers: 12
  encoder_reparameterization_type: "MLP"
  encoder_hidden_size: 4096

data:
  train_split: train
  val_split: validation
  dataset:
    dataset_name: "RazinAleks/SO-Python_QA-"  #"RazinAleks/SO-Python_QA-Database_and_SQL_class"
    max_length: 768
    max_prompt_length: 512
    use_title: true
    filter_zero_scores: true

training_arguments:
  seed: 42
  num_train_epochs: 10
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  learning_rate: 0.00003 #1.0e-04
  optim: "adamw_torch"
  # Oprims: adamw_hf/adamw_torch/adamw_torch_fused/adamw_apex_fused/adamw_anyprecision/adafactor
  weight_decay: 0.2
  adam_beta1: 0.9
  adam_beta2: 0.99
  max_grad_norm: 1

  ### LR SCHEDULER ###
  # TYPES: linear/cosine/cosine_with_restarts/polynomial/constant/constant_with_warmup
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.01

  ### MEMORY OPTIMIZATION ###
  gradient_accumulation_steps: 1 # !
  fp16: true
  gradient_checkpointing: true

  ### EVALUATION ###
  evaluation_strategy: "steps" # steps/epoch
  eval_steps: 0.05 ## 650 steps, 0.05*650 = 33 step
  fp16_full_eval: true
  logging_first_step: true
  prediction_loss_only: true
  remove_unused_columns: false
  dataloader_drop_last: false
  # predict_with_generate: false

  ### SAVING ###
  save_strategy: "steps" #steps/epoch; if steps needs `save_steps`
  save_steps: 0.05
  output_dir: /home/st-aleksandr-razin/workspace/SRC_QC4QA/QA_pipeline/artifacts/experiments/
  save_total_limit: 1
  load_best_model_at_end: true
  resume_from_checkpoint: null

  ### LOGGING CONFIG ###
  logging_strategy: "steps"
  logging_steps: 1
  report_to: 'wandb'
  #run_name: "train-ptune-llama-Web_Development_class-7b-bs_16-lr_3e4-m_l_1280-m_p_l_768-num_toks_512-w_decay_0.2"

# generation_config:
#   do_sample: true
#   max_new_tokens: 512
#   no_repeat_ngram_size: 2
#   top_k: 50
#   top_p: 0.9